name: Push deploy
on: push
jobs:
  push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push it
        run: |
          curl -XPOST -u "${{ secrets.REPO_DOCS_DEPLOY_USERNAME }}:${{ secrets.REPO_DOCS_DEPLOY_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${{ secrets.REPO_DOCS_DEPLOY }}/dispatches --data '{"event_type": "build_application"}'
